# Generated by Django 5.1.6 on 2025-02-26 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_message_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='store',
        ),
    ]
